### ISSUE TITLE
About the model Unlearning (MCU)

### ISSUE THREAD

**Issue by Ideal-Bushgorman** [dzp2095/FCU#1]
HI ! I'm really interested in your work. But I don't fully understand the MCU block. With the model contrastive unlearning, the unlearned model should be similar to the downgraded model, a model pretrained on ImageNet, why doesn't it deteriorate the global model since the pretrained model doesn't benefits to the task?

**Comment by dzp2095** [comment]
Hi! Thank you for reaching out. Yes, you're absolutely right. The MCU block alone would indeed make the unlearned model resemble the downgraded model. To address this, we use frequency-guided memory preservation to retain the globally learned, generalized knowledge. Additionally, we apply several rounds of post-training (excluding the requesting client) to help the unlearned model recover its performance. I hope this would answer your question.
